### ISSUE TITLE
More information regarding How to Use

### ISSUE THREAD

**Issue by ragingprodigy** [idleberg/vscode-svg-icons#1] opened 2017-02-12 07:50 UTC
Hello,

Nice plugin you have here. I just installed it but I don't seem to know how to use it. The usage part of the README isn't sufficient.

> Snippets are limited to the html scope. Typing the class name of an icon using the designated prefix will complete to a SVG tag for the icon.

I've typed `bi` and `bi-close` and also done `<i class="bi">`, `<svg class="bi">` without getting any suggestions.

Thanks

**Comment by idleberg** [comment] 2017-02-12 10:18
Thanks for reporting, this was caused by an incorrect file-name. Should be fixed in `v0.2.3`. Since you seem to like the package, I'd appreciate a rating on [Marketplace](https://marketplace.visualstudio.com/items?itemName=idleberg.svg-icons) 😄 

Regarding usage: I will add an animated screenshot in one of the upcoming releases!

**Closed as completed** 2017-02-14 09:00 UTC

**Comment by ragingprodigy** [comment] 2017-02-22 09:31
Done
